### ISSUE TITLE
Error en documentación.

### ISSUE THREAD

**Issue by Uriel767** [J-Pyrsa/branding-jpyrsa-zabbix#2]
El primer error encontrado es en el apartado "Cambio de logos predeterminados ..." cuando se nos da la instrucción de poner los logos se coloco en el apartado de código el comando "mkdir" el cual no tiene propósito y marca error al compilar dado que no tiene operando.

![image](https://github.com/J-Pyrsa/branding-jpyrsa-zabbix/assets/163465994/34b4bf23-bd45-4ba4-9b08-4ecbe0a3f1de)

El segundo error encontrado es en el apartado "Asignación del tema" el cual nos muestra que hay que agregar un "theme" pero no se nos menciona el nombre del archivo ni el hecho de tener que editar el archivo con el comando "nano APP.php".

![image](https://github.com/J-Pyrsa/branding-jpyrsa-zabbix/assets/163465994/9157ed1f-9219-4cc4-b6c9-9ae2d9fa02b0)

Favor de corregir dichos errores los cuales pueden causar confusión al momento de seguir la documentación conduciéndonos a errores al querer hacer los cambios ya mencionados.

**Comment by erwinpalma** [comment]
Corregido en la versión zabbix_7
